runtime: php83

entrypoint: serve public/index.php

default_expiration: '180d'

handlers:
- url: /assets/css
  static_dir: public/assets/css
  expiration: '30d'

- url: /assets/js
  static_dir: public/assets/js
  expiration: '30d'

- url: /assets/fonts
  static_dir: public/assets/fonts

- url: /assets/images
  static_dir: public/assets/images
  expiration: '60d'

- url: /manifest.json
  static_files: public/manifest.json
  upload: public/manifest.json

- url: /browserconfig.xml
  static_files: public/browserconfig.xml
  upload: public/browserconfig.xml

- url: /node_modules
  static_dir: public/node_modules
  expiration: '30d'

- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301
